include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false